### ISSUE TITLE
MultiK2_win32

### ISSUE THREAD

**Issue by rfilkov** [jmarcincin/MultiK2#1]
Hello Jan,

Impressive, really impressive! My only issue so far is that I could not compile MultiK2_win32 and the respective DesktopKinect-client. They reference a Windows-assembly, which is not available in my VS2015. I tried to replace it with references to the existing Windows.Media, Windows.Graphics, Windows.Foundation, etc., but this caused a lot of other errors. What did I do wrong? May Windows be a library coming with more recent OS update?

Greetings!

**Comment by jmarcincin** [comment]
You need Windows SDK for W10 1607 (14393) / Windows 10 1607 installed to run it. 
_VS2015 installer > Features > Universal Windows App Development Tools > Tools (1.4.1) and Windows SDK (10.0.0.14393)_

If you have it installed and still experience described issue:
To compile the win32 "desktop" library you need to fix a reference to Windows winmd. This metadata file is located in 
_Program Files (x86)\Windows Kits\10\UnionMetadata\Windows.winmd_

see: https://github.com/jbe2277/waf/wiki/Using-Windows-Runtime-in-a-.NET-desktop-application

I intend to replace hardcoded hint path with the environment variable to Program files (x86) folder in the next commit.

**Comment by jmarcincin** [comment]
project file update with relative path to Windows metadata & Windows Runtime library is part of https://github.com/jmarcincin/MultiK2/commit/708230ee9ed68a54c9b6b229641b6c480448252a
